# role tasks
- name: Find the current locale setting
  slurp:
    src: /etc/locale.conf
  register: host_locale

- name: Update locale if needed
  become: "{{ localectl_become }}"
  become_user: "{{ localectl_become_user }}"
  command: localectl set-locale LANG="{{ localectl_locale }}"
  when: localectl_locale not in host_locale.content | b64decode

# Grep vconsole.conf file to ignore comments and
# exactly match and return the line that includes KEYMAP=
- name: Find the current keymap setting
  become: "{{ localectl_become }}"
  become_user: "{{ localectl_become_user }}"
  shell: |
    set -o pipefail | grep /etc/vconsole.conf -v -e '^#' |
    sed -E -e 's/#.*$//' | grep KEYMAP'='
  register: keymap
  changed_when: "keymap.rc != 0"

- name: Update keymap if needed
  become: "{{ localectl_become }}"
  become_user: "{{ localectl_become_user }}"
  command: >
      localectl set-keymap --no-convert "{{ localectl_keymap }}"
  when: localectl_keymap not in keymap.stdout

- name: Find the current x11_keymap setting
  slurp:
    src: /etc/X11/xorg.conf.d/00-keyboard.conf
  register: host_x11_keymap

- name: Make myx11keymap var
  set_fact:
    myx11keymap: 'XkbLayout" "{{ localectl_x11_keymap }}'

- name: Update x11keymap if needed
  become: "{{ localectl_become }}"
  become_user: "{{ localectl_become_user }}"
  command: >
    localectl set-x11-keymap --no-convert "{{ localectl_x11_keymap }}"
  when: myx11keymap not in host_x11_keymap.content | b64decode
